# For more information, please refer to https://aka.ms/vscode-docker-python
FROM ubuntu:latest

# Keeps Python from generating .pyc files in the container
ENV PYTHONDONTWRITEBYTECODE=1

# Turns off buffering for easier container logging
ENV PYTHONUNBUFFERED=1

# set workdir to /tmp
WORKDIR /tmp

# copy v97, install v97
COPY mcr_v97.zip .
RUN apt-get update && apt-get install unzip
RUN unzip mcr_v97.zip -d mcr_v97
RUN cd mcr_v97 && ./install -mode silent -agreeToLicense yes
RUN rm mcr_v97.zip && rm -r mcr_v97

# change workdir to /rcwa

# Install python and pip requirements
RUN apt-get install -y python3 python3-pip
RUN apt-get install -y python3-venv
WORKDIR /rcwa
COPY requirements.txt .
RUN python3 -m venv .venv && . .venv/bin/activate && pip install -r requirements.txt

# copy rcwa_comp, rcwa_slave.py, ld_library_path to /rcwa/
COPY rcwa_comp rcwa_slave.py ld_library_path ./

# copy setup.sh to /rcwa
COPY setup.sh .

# setup bash as default shell
SHELL ["/bin/bash", "-o", "pipefail", "-c"]

# run setup.sh
CMD ["./setup.sh"]
# CMD ["./setup.sh", ". .venv/bin/activate && python rcwa_slave.py"]
