FROM ubuntu:22.04

# workdir
WORKDIR /tmp

# use bash
SHELL ["/bin/bash", "-o", "pipefail", "-c"]

# install python3, python3-pip, python3-venv
RUN apt-get update && apt-get install -y python3 python3-pip python3-venv && \
    apt-get clean && rm -rf /var/lib/apt/lists/*

